sql {
	dialect = "postgresql"
	driver = "rlm_sql_postgresql"

	postgresql {
		send_application_name = yes
	}

	server = "@RADIUS_DB_HOST@"
	port = 5432
	login = "@RADIUS_DB_USER@"
	password = "@RADIUS_DB_PASSWORD@"
	radius_db = "@RADIUS_DB_NAME@"

	acct_table1 = "radacct"
	acct_table2 = "radacct"
	postauth_table = "radpostauth"
	authcheck_table = "radcheck"
	authreply_table = "radreply"
	groupcheck_table = "radgroupcheck"
	groupreply_table = "radgroupreply"
	usergroup_table = "radusergroup"

	delete_stale_sessions = yes
	read_groups = yes
	read_clients = yes
	client_table = "nas"

	pool {
		start = 0
		min = 0
		max = 8
		spare = 1
		idle_timeout = 30
		connect_timeout = 5
	}

	$INCLUDE ${modconfdir}/${.:instance}/main/${dialect}/queries.conf
}
